manipulator:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  joint1_position:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 300.0, i: 1, d: 2}
  
  joint2_position:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 300.0, i: 1, d: 2}
  
  joint3_position:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 300.0, i: 1, d: 2}
  
  joint4_position:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 300.0, i: 1, d: 2}
  
  joint5_position:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 300.0, i: 1, d: 2}
  
  gripper_position_l:
    type: effort_controllers/JointPositionController
    joint: joint_gripper_l
    pid: {p: 100, i: 0, d: 0}
  gripper_position_r:
    type: effort_controllers/JointPositionController
    joint: joint_gripper_r
    pid: {p: 100, i: 0, d: 0}